### ISSUE TITLE
Exported excel file corrupted

### ISSUE THREAD

**Issue by chamath** [yii2tech/spreadsheet#14]
I tried to export excel as given example using following code

`      	$exporter = new Spreadsheet([
    			'dataProvider' => new ActiveDataProvider([
    					'query' => Subject::find(),
    					'pagination' => [
    							'pageSize' => 100, // export batch size
    					],
    			]),
    	]);
    	return $exporter->send('items.xls'); `

Unfortunately it generates corrupted file. Please find the attachment. 
![export_excel](https://user-images.githubusercontent.com/2102672/49437659-1c0bb900-f7e2-11e8-8639-77d2ace9d97b.PNG)

May I know where am I wrong? Do we need to add headers as well? Is there any proper documentation except README?

Thanks

**Comment by klimov-paul** [comment]
Check documentation of [phpoffice/phpspreadsheet](https://github.com/PHPOffice/PhpSpreadsheet) library for the solution.

**Comment by chamath** [comment]
Thanks @klimov-paul 
I used ob_end_clean() before calling spreadsheet as follows. Is this the correct way? 
        ob_end_clean();
      	$exporter = new Spreadsheet([
    			'dataProvider' => new ActiveDataProvider([
    					'query' => $query_outer,
    					'pagination' => [
    							'pageSize' => 100, 
    					],
    			]),
    	]);
    	return $exporter->send('items.xls');
