### ISSUE TITLE
Permission denied with Xlsx writer

### ISSUE THREAD

**Issue by Slayvin** [yii2tech/spreadsheet#18]
I get an error message when using Spreadsheet::send and Xlsx writer saying:

> unlink(...\AppData\Local\Temp\php3945.tmp): Permission denied

`$tmpResource` needs to be closed before `$writer->save($tmpFileName)`

```php
// ...
$tmpResourceMetaData = stream_get_meta_data($tmpResource);
$tmpFileName = $tmpResourceMetaData['uri'];

$tmpFileStatistics = fstat($tmpResource);
if ($tmpFileStatistics['size'] > 0) {
    return Yii::$app->getResponse()->sendStreamAsFile($tmpResource, $attachmentName, $options);
}

fclose($tmpResource);
$writer = IOFactory::createWriter($this->getDocument(), $writerType);
$writer->save($tmpFileName);
unset($writer);
// ...
``` 
 The code above is working for .xls or .xlsx, I didn't try with other formats

**Comment by klimov-paul** [comment]
Unable to reproduce.

**Comment by OndrejVasicek** [comment]
I have the same problem, the same error message. The changes Slayvin had done really helped.

Win 10
PHP 7.1.4
Yii 2.0.25
