### ISSUE TITLE
Is there any way to add image as header, before data grid

### ISSUE THREAD

**Issue by baltechies** [yii2tech/spreadsheet#22]
Hi,

Is there any function to add image and title in data sheet before main data table?

**Comment by klimov-paul** [comment]
You can control the rendering start logic using [Spreadsheet::$startRowIndex](https://github.com/yii2tech/spreadsheet/blob/master/src/Spreadsheet.php#L173-L178).
You may set to be further that 1st row and then fill the blanks [manually](https://github.com/yii2tech/spreadsheet#custom-cell-rendering-).
