### ISSUE TITLE
Add possibility to configure PhpOffice\PhpSpreadsheet\Writer

### ISSUE THREAD

**Issue by TechTopcomputer** [yii2tech/spreadsheet#23]
### What steps will reproduce the problem?
If export to Csv some text with non latin symbos i get charset errored text.

### What is the expected result?
In csv i try to see readable data such as "Несколько слов на русском языке"

### What do you get instead?
I see data in wrong charset as "Р°РєС‚РёРІРЅР°"

### Additional info
Problem can be solwed with possibility to configure writer such as:

```
$writer = IOFactory::createWriter($this->getDocument(), $writerType);
if ($writerType=='Csv') {$writer->useBOM=true;}
$writer->save($filename);
```

OR

```
$writer = IOFactory::createWriter($this->getDocument(), $writerType);
if ($writerType=='Csv') {$writer->excelCompatibility=true;}
$writer->save($filename);
```

OR 

add $this->writerConfig property to yii2tech\spreadsheet\Spreadsheet and apply it to $writer

OR

create new method and use it to get $writer (so i can use extend yii2tech\spreadsheet\Spreadsheet of it )
```
publick function createWriter($writerType){
      return IOFactory::createWriter($this->getDocument(), $writerType);
}
```

**!!! Please, add possibility to configure writer!**

| Q                                  | A
| ---------------------------------- | ---
| This Package Version               | 1.0.4
| Yii Framework Version              | 2.0.13
| "phpoffice/phpspreadsheet" Version | 1.8.2
| PHP version                        |  7.0
| Operating system                   | ubuntu 16

**Comment by klimov-paul** [comment]
Resolved by commit 455007f35701eef697f705c04da8241eb5e60e4d
