### ISSUE TITLE
how to set datatype

### ISSUE THREAD

**Issue by sanwv** [yii2tech/spreadsheet#25]
### Additional info

| Q                                  | A
| ---------------------------------- | ---
| This Package Version               | 1.?.?
| Yii Framework Version              | 2.0.?
| "phpoffice/phpspreadsheet" Version | 1.?.?
| PHP version                        | 
| Operating system                   |

e.g. force set a number show as string, like 

```
$cell->setCellValueExplicit(
    'A8',
    "01513789642",
    \PhpOffice\PhpSpreadsheet\Cell\DataType::TYPE_STRING
);
```
```
$cell->setDataType(
    \PhpOffice\PhpSpreadsheet\Cell\DataType::TYPE_STRING
);
```

**Comment by klimov-paul** [comment]
Duplicates #17
