### ISSUE TITLE
Howto specify attributes for related tables?

### ISSUE THREAD

**Issue by WeeSee** [yii2tech/spreadsheet#28]
Great repo!

I want to change the label of an attribute of a related table. How can I specify attributes for related tables?

I tried:

```
'attributes' => [
    'myattrib1',  // works
    'othertable.myattrib2', // works
    [
        'attribute' => 'othertable.myattrib2', // doesn't work
        'label' => 'NewLabel',
    ]
]
```

**Comment by klimov-paul** [comment]
Unable to reproduce.
Although I doubt the code snippet you have provided is actually functional, since there is no field or property named `attributes` neither at `Spreadsheet` nor at 'DataColumn'.

The correct code should look like following:

```
$exporter = new Spreadsheet([
    // ...
    'columns' => [
        [
            'attribute' => 'othertable.myattrib2',
            'label' => 'NewLabel',
        ],
        // ...
    ],
]);
```
