### ISSUE TITLE
Allowed memory size

### ISSUE THREAD

**Issue by degorych** [yii2tech/spreadsheet#30]
I get error for 8000+ array items
Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes)

| Q                                  | A
| ---------------------------------- | ---
| This Package Version               | 1.0.2
| Yii Framework Version              | 2.0.15
| "phpoffice/phpspreadsheet" Version | not found in composer
| PHP version                        |  7.2
| Operating system                   | ubuntu 18

```
$orders = [...] // Array of 8000+ items

// item example
// 0 => [
//    "id" => "146472", "created" => "2021-06-01 17:01:28", "site", => "1", "status" => "Отменён", 
//    "address_to_delivery" => "Кропивницкий - 1", "price" => "956", "restaurant"=> "0", "delivery_datetime" => "14:33", 
//    "first_name" => "Дмитрий", "phone" => "0662784754", "start_delivery" => "Не передано курьеру" , 
//   "complited_draw_order" => "2021-06-01 17:02:30", "items_num" => "0", "pizzeria" => "К1", "marketing" => "Нет",
//    "promo" => "", "timeDelivery" => "Да"]

var_dump($orders); // This work

$dataProvider = new ArrayDataProvider([
            'allModels' => $orders,
            'pagination' => [
                'pageSize' => 100,
            ],
        ]);

$exporter = new Spreadsheet([
            'dataProvider' => $dataProvider,
            'title' => 'Orders',
            'columns' => [...],
            'batchSize' => 200,]);

return $exporter->send('Заказы с ' . $date_from . ' по '.$date_to . '.xls');
```

If number of items 6000 this is work correctly
![Screenshot (11)](https://user-images.githubusercontent.com/32522147/121666076-8d164080-cab1-11eb-893c-5f0761739af1.png)

**Comment by klimov-paul** [comment]
https://github.com/yii2tech/spreadsheet/blame/1.0.5/README.md#L208-L212
