### ISSUE TITLE
Can I return a base64 instead of saving the file?

### ISSUE THREAD

**Issue by zeusworkspace** [yii2tech/spreadsheet#6]
I'm using PHPSpreadsheet to generate an Excel file that I want to attach to a mail message, together with a bunch of PDF files(using Mpdf).

With Mpdf I can simply do:  `return base64_encode($mpdf->Output())`

and attach it to the email with:

```
 $file = base64_decode($this->actiongetPdfFile($postData['billing_profile']));

$message->attachContent($file, ['fileName' => 'file.pdf', 'contentType' => 'data:application/pdf']);
```
Is there a way to do something similar with PHPSpreadsheet (without the need to save the file to disk before)?

I saw that suggestions saying that it was possible using $objWriter->save('php://output');, but this did not work with this plugin.

I believe that there is no further documentation aside from what is already on the initial page, right?

**Comment by Et3rnel** [comment]
Did you find any solution to send the file as an attachment without having to saving it on the disk ?

**Comment by ArvidDeJong** [comment]
I am intrested too :)
