### ISSUE TITLE
Problems in console

### ISSUE THREAD

**Issue by ettolo** [yii2tech/spreadsheet#9]
Hi, thank you for this extension.
I'm trying to save a xls file from console but I get this error:
`PHP Parse error:  syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /home/****/vendor/yii2tech/spreadsheet/src/Spreadsheet.php on line 222`
The same code works perfectly if called from the browser.
Any Idea?
Tryed in a different server and it works, but also tryed a different extension in the same server and works perfecty. Also your csv exporter works in both servers

**Comment by klimov-paul** [comment]
I can not debug your environment for you.
Make sure PHP web handler and console handler refer to the same PHP instance, have same version and same php.ini config.

**Comment by ettolo** [comment]
Thank you, think you pointed me to the right solution!
